### ISSUE TITLE
Add Color Map to Step Metadata for Object (Instance Segmentation) Mask Colors

### ISSUE THREAD

**Issue by ThomasSchellenbergNextCentury** [NextCenturyCorporation/MCS#240]
From: Ben, Falk https://machinecommonsense.slack.com/archives/CTR31V12M/p1594750155073000

Priority: Backlog

Components: Python API

Blockers: None

Steps:
- Remove “color” from ObjectMetadata
- Add “color_map” to StepMetadata
  - A Dict with object ID string keys and color pixel array values
  - Use scene_event.metadata['colors'] but reformat it
  - Should only be used in Oracle Metadata Mode
- Update the unit tests

TA2 internal JIRA ticket: https://nextcentury.atlassian.net/browse/MCS-318

**Comment by deanwetherby** [comment]
The slack thread differs slightly from this ticket's description. I'm not sure I fully understand the index suggestion from @fplk's slack comment included below. Can I get some clarity on this idea from @fplk and @bzinberg?

https://machinecommonsense.slack.com/archives/CTR31V12M/p1594750434074000?thread_ts=1594750155.073000&cid=CTR31V12M

**Comment by ThomasSchellenbergNextCentury** [comment]
@deanwetherby Hope you don't mind me joining this conversation:

It's been a while, so I'm trying to remember how I got from that Slack thread to this Issue's description. I believe my logic flow was as follows:
- Ben asked about the `ObjectMetadata.color` property
- Falk explained its use
- Ben commented about using "ids and a color map" instead
- People made other comments

So I think I grabbed onto Ben's comment and translated it into this Issue. I won't speak to Falk's comment about tuples since I'm not exactly sure what he meant by it. It's also possible that this feature is coming too late and/or no longer of interest. Hoping that this helps to shed a little more context.

**Comment by deanwetherby** [comment]
@ThomasSchellenbergNextCentury that was my understanding as well. I would like to understand the idea behind 0-based indexing over using an object ID key as well as the preferences on a data structure for the color value before I fully implement.

**Comment by bzinberg** [comment]
Thanks @deanwetherby and @ThomasSchellenbergNextCentury for looking into this.

99% of my concern on that thread was about the field name, actually.  Since that field has the semantics of "segment id"[^1], calling the field `color` seemed likely to cause confusion down the line, especially for new people coming onboard who haven't seen this conversation.  And especially since the objects _also_ have actual colors, which this field does not have anything to do with.

Certainly no need for a color map.  In fact, AFAIK, the actual color indicated by these values has no significance at all, it's just an opaque identifier for the segment, right?  This might be an important point to clarify, because at present I don't know what the color map you are considering implementing would mean.

If we simply rename the field to something like `segment_id`, I'm happy.  Two possible bonuses:
1. Change the data type to something hashable/immutable/POD that has an obvious string equivalent (for example, a string), so it can be serialized/deserialized easily by foreign code.
2. Change the naming scheme to something that doesn't look like a different data type (in this case, like a color, when the semantics is not one of actual colors).  Otherwise, by [Hyrum's Law](https://www.hyrumslaw.com/), someone will later depend on having undocumented color semantics.

[^1] or "object id"? idk, so far we haven't had instances of a single object with two connected components

**Comment by deanwetherby** [comment]
@flpk and @bzinberg, we are getting closer to merging this PR. Curious if this adequately addresses the request.

**Comment by bzinberg** [comment]
Thanks, chimed in there - https://github.com/NextCenturyCorporation/MCS/pull/413#issuecomment-929571442.

**Comment by bzinberg** [comment]
Thanks for this fix!  X-ref some extra comments I left in https://github.com/NextCenturyCorporation/MCS/pull/413#issuecomment-930625678 in case helpful.
