### ISSUE TITLE
Top object falls through support object

### ISSUE THREAD

**Issue by bzinberg** [NextCenturyCorporation/MCS#253]
After updating to MCS Python library 0.3.8, Unity app 0.3.8, the simulation of [`gravity_support_ex_01.json`](https://github.com/NextCenturyCorporation/MCS/blob/0.3.8/machine_common_sense/scenes/gravity_support_ex_01.json) looks like this:

[video](https://drive.google.com/file/d/1p3QPjEUON2h1RHO6OGHBbl0U8nwb54nc/view?usp=sharing)

In Python library 0.3.7, Unity app 0.3.7, it looked like this, which I think is the intended result:

[video](https://drive.google.com/file/d/1KMWfHzEAa_Zsv-wk939XgBNt_otMSNdA/view?usp=sharing)

My OS and hardware are as [here](https://github.com/NextCenturyCorporation/MCS/issues/228#issuecomment-774279272) and my Python environment is as [here](https://github.com/NextCenturyCorporation/MCS/issues/228#issuecomment-787000782).

**Comment by deanwetherby** [comment]
Thanks for opening this issue @bzinberg. We'll get right on that.

**Comment by ThomasSchellenbergNextCentury** [comment]
@bzinberg The issue was in the example gravity support scene files. The support objects must have the `kinematic: true` and `structure: true` properties set. I've updated the scene files in our repository (they'll be merged soon); you can see the corresponding PR here: https://github.com/NextCenturyCorporation/MCS/pull/254

Please note that the Scene Generator correctly sets these properties in gravity support scenes.

**Comment by bzinberg** [comment]
Thanks for the quick response @deanwetherby @ThomasSchellenbergNextCentury, and for linking the fix!  I take it 0.3.7 was behaving as if these properties were set by default, so it was purely a plumbing issue?

**Comment by ThomasSchellenbergNextCentury** [comment]
Yes, that is correct.
